### ISSUE TITLE
Please Help!

### ISSUE THREAD

**Issue by burakaksahin** [Hitman666/nbCcTalkCoinAcceptor#6]
very successful project. But 4. and 5. channels does not recognize the money. What is the reason?

/// <summary>
        /// 1=2=2EUR; 2=1=1EUR; 3=0,5=50 cent; 4=0,2=20 cent; 5=0.1=10 cent; 6=0.05=5cent;		
        /// </summary>
        public static Dictionary<byte, CoinTypeInfo> DefaultConfig = new Dictionary<byte, CoinTypeInfo>
		{		
			{1, new CoinTypeInfo("5 Krs",	0.05M)},						
			{2, new CoinTypeInfo("10 Krs",	0.10M)},
			{3, new CoinTypeInfo("25 Krs", 0.25M)},
			{4, new CoinTypeInfo("50 Krs", 0.50M)},
			{5, new CoinTypeInfo("1 TL", 1M)},
			{6, new CoinTypeInfo("0 TL", 0M)},
		};

**Comment by Hitman666** [comment]
It could be that your actual device is programmed that way. Is there a way for you to check that?

**Comment by Hitman666** [comment]
Solved, as per your other comment.
