### ISSUE TITLE
Thank You....

### ISSUE THREAD

**Issue by burakaksahin** [Hitman666/nbCcTalkCoinAcceptor#7]
thank you bro. I solved the problem.

Old:
_coinAcceptor.AllowedCoins = CoinIndex.One | CoinIndex.Two | CoinIndex.Three;

New:
_coinAcceptor.AllowedCoins = CoinIndex.One | CoinIndex.Two | CoinIndex.Three | CoinIndex.Four | CoinIndex.Five;

**Comment by Hitman666** [comment]
No problem, glad you found a way in the end!
